name: example_web_server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  args: ^2.3.1
  encrypt:
  hive: ^2.2.2
  pointycastle:
  shelf: ^1.3.0
  shelf_multipart: ^1.0.0
  blowfish_ecb: ^0.1.0
  shelf_plus: ^1.4.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
  shelf_web_socket: ^1.0.2
  meta: ^1.8.0
  dio: ^4.0.6
#   path: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
